server:
  port: 8083

spring:
  application:
    name: credits-service
  config:
    import: "optional:configserver:http://localhost:8888"  # Configuración correcta para importar desde Config Server

  data:
    mongodb:
      uri: mongodb://localhost:27017/creditsdb

logging:
  level:
    root: INFO

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha