spring:
  application:
    name: ms-operation
  servlet:
    context-path: /ms-operation
  data:
    mongodb:
      uri: mongodb+srv://user_1801:1234@bootcamp.4q2qjnr.mongodb.net/SISTEMA_BANCARIO?retryWrites=true&w=majority&appName=bootcamp

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    hostname: ${COMPUTERNAME:localhost}

server:
  port: 8084